
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author officeworks
 */
public class FetchVideos extends javax.swing.JPanel {

    /**
     * Creates new form FetchVideos
     */
    public FetchVideos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        bt_play = new javax.swing.JButton();
        bt_download = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(null);

        lb1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lb1);
        lb1.setBounds(30, 40, 130, 110);

        lb2.setText("Lecture no");
        add(lb2);
        lb2.setBounds(20, 170, 100, 30);

        lb3.setText("Title");
        add(lb3);
        lb3.setBounds(20, 210, 80, 20);

        lb4.setText("Duration");
        add(lb4);
        lb4.setBounds(20, 240, 60, 30);

        bt_play.setIcon(new javax.swing.ImageIcon("C:\\Users\\officeworks\\Desktop\\photos\\download.play.png")); // NOI18N
        bt_play.setEnabled(false);
        bt_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_playActionPerformed(evt);
            }
        });
        add(bt_play);
        bt_play.setBounds(130, 240, 40, 30);

        bt_download.setIcon(new javax.swing.ImageIcon("C:\\Users\\officeworks\\Desktop\\photos\\download.download.png")); // NOI18N
        bt_download.setEnabled(false);
        add(bt_download);
        bt_download.setBounds(183, 240, 30, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_playActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_playActionPerformed


    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bt_download;
    public javax.swing.JButton bt_play;
    public javax.swing.JLabel lb1;
    public javax.swing.JLabel lb2;
    public javax.swing.JLabel lb3;
    public javax.swing.JLabel lb4;
    // End of variables declaration//GEN-END:variables
}
