
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.event.ActionEvent;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author officeworks
 */
public class ForgotPass extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPass
     */
    String contact, password;
    int otp;

    public ForgotPass() {
        initComponents();
        setSize(600, 600);
        setLocation(275,100);
        lb_pa.setVisible(false);
        tf_otp.setVisible(false);
        //jLabel1.setVisible(false);
        bt_ne.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_em = new javax.swing.JTextField();
        bt_cont = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_otp = new javax.swing.JTextField();
        bt_ne = new javax.swing.JButton();
        lb_pa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Enter email");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, 10, 110, 40);

        tf_em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emActionPerformed(evt);
            }
        });
        getContentPane().add(tf_em);
        tf_em.setBounds(120, 10, 200, 40);

        bt_cont.setBackground(new java.awt.Color(204, 255, 255));
        bt_cont.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_cont.setText("Continue");
        bt_cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_contActionPerformed(evt);
            }
        });
        getContentPane().add(bt_cont);
        bt_cont.setBounds(100, 70, 150, 40);

        jLabel2.setText("An OTP is sent to ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(14, 130, 350, 50);

        jLabel3.setText("Enter OTP");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(4, 200, 80, 30);
        getContentPane().add(tf_otp);
        tf_otp.setBounds(120, 200, 100, 30);

        bt_ne.setBackground(new java.awt.Color(204, 255, 204));
        bt_ne.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_ne.setText("Next");
        bt_ne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_neActionPerformed(evt);
            }
        });
        getContentPane().add(bt_ne);
        bt_ne.setBounds(100, 260, 130, 40);

        lb_pa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_pa.setText("Your password is ");
        getContentPane().add(lb_pa);
        lb_pa.setBounds(40, 370, 350, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_emActionPerformed

    private void bt_contActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_contActionPerformed
        bt_cont.setEnabled(false);
        new Thread(new job_fordi()).start();
    }//GEN-LAST:event_bt_contActionPerformed

    private void bt_neActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_neActionPerformed
        // TODO add your handling code here:
        lb_pa.setVisible(true);
        sms_sender obj=new sms_sender();
        
       if (tf_otp.getText().equals(otp + "")) {
            lb_pa.setText(password);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please enter correct OTP!!!!");
        }
    }//GEN-LAST:event_bt_neActionPerformed

    class job_fordi implements Runnable {

        //  Logger.getLogger(ForgotPass.class.getName()).log(Level.SEVERE, null, ex);
        //ex.printStackTrace();}
        @Override
        public void run() {
            //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            String numb;
            try {
                // TODO add your handling code here:
                HttpResponse res = Unirest.get("http://"+GlobalData.host+"/forgotpassword").queryString("email", tf_em.getText()).asString();
                StringTokenizer st = new StringTokenizer(res.getBody().toString(), ";");

                contact = st.nextToken();
                password = st.nextToken();
lb_pa.setText("Your password is: ");
                lb_pa.setVisible(true);
                tf_otp.setVisible(true);
                //jLabel1.setVisible(false);
                bt_ne.setVisible(true);
                jLabel2.setVisible(true);
                jLabel3.setVisible(true);

                numb = "******" + contact.substring(8);
                jLabel2.setText("An OTP is sent on:" + numb);
                otp = (int) (1000 + 8999 * Math.random());
                String message="OTP to make payment is:"+otp;
                System.out.println(otp);
                sms_sender obj=new sms_sender();
                obj.send(contact,message);
                obj.send(contact,"you successfully made payment");

            } catch (UnirestException ex) {
                ex.printStackTrace();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPass.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPass.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPass.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPass.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cont;
    private javax.swing.JButton bt_ne;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lb_pa;
    private javax.swing.JTextField tf_em;
    private javax.swing.JTextField tf_otp;
    // End of variables declaration//GEN-END:variables
}
