
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author officeworks
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        setVisible(true);
        setSize(550, 550);
        setLocation(250,80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_em = new javax.swing.JTextField();
        tf_na = new javax.swing.JTextField();
        tf_pa = new javax.swing.JPasswordField();
        tf_cpa = new javax.swing.JPasswordField();
        tf_phn = new javax.swing.JTextField();
        tf_pho = new javax.swing.JTextField();
        bt_bro = new javax.swing.JButton();
        bt_sign = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SignUp");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 0, 150, 40);

        jLabel2.setText("Enter Email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 100, 20);

        jLabel3.setText("Enter phone");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 270, 80, 20);

        jLabel4.setText("Enter Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 100, 80, 50);

        jLabel5.setText("Enter Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 160, 100, 30);

        jLabel6.setText("Confirm Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 210, 100, 30);

        jLabel7.setText("Select Photo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 330, 100, 30);
        getContentPane().add(tf_em);
        tf_em.setBounds(120, 60, 170, 30);
        getContentPane().add(tf_na);
        tf_na.setBounds(120, 110, 170, 30);
        getContentPane().add(tf_pa);
        tf_pa.setBounds(120, 160, 170, 30);
        getContentPane().add(tf_cpa);
        tf_cpa.setBounds(120, 210, 170, 40);
        getContentPane().add(tf_phn);
        tf_phn.setBounds(120, 270, 170, 40);
        getContentPane().add(tf_pho);
        tf_pho.setBounds(120, 330, 170, 40);

        bt_bro.setText("Browse");
        bt_bro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_broActionPerformed(evt);
            }
        });
        getContentPane().add(bt_bro);
        bt_bro.setBounds(330, 330, 100, 40);

        bt_sign.setText("Sign Up");
        bt_sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_signActionPerformed(evt);
            }
        });
        getContentPane().add(bt_sign);
        bt_sign.setBounds(120, 390, 150, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_signActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_signActionPerformed
        if (tf_cpa.getText().equals("") || tf_em.getText().equals("") || tf_na.getText().equals("") || tf_pa.getText().equals("") || tf_phn.getText().equals("") || tf_pho.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Fill all details");
        } else if (!tf_cpa.getText().equals(tf_pa.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Your password doesnot match");
        } else {
            new Thread(new job_signup()).start();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_signActionPerformed
    File f;
    private void bt_broActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_broActionPerformed
        JFileChooser jf = new JFileChooser();
        int r = jf.showOpenDialog(this);
        if (r == JFileChooser.APPROVE_OPTION) {
            f = jf.getSelectedFile();
        }
        tf_pho.setText(f.getPath());
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_broActionPerformed

    // TODO add your handling code here:
    class job_signup implements Runnable {

        @Override

        /**
         *
         */
        public void run() {
            try {
                HttpResponse res = Unirest.post("http://"+GlobalData.host+"/signup").queryString("email", tf_em.getText())
                        .queryString("phone", tf_phn.getText())
                        .queryString("password", tf_pa.getText())
                        .queryString("name", tf_na.getText())
                        .field("photo", new File(tf_pho.getText()))
                        .asString();
                JOptionPane.showMessageDialog(rootPane, "Success");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_bro;
    private javax.swing.JButton bt_sign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField tf_cpa;
    private javax.swing.JTextField tf_em;
    private javax.swing.JTextField tf_na;
    private javax.swing.JPasswordField tf_pa;
    private javax.swing.JTextField tf_phn;
    private javax.swing.JTextField tf_pho;
    // End of variables declaration//GEN-END:variables
}
