
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import javax.swing.JOptionPane;
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author officeworks
 */
public class UserLogin extends javax.swing.JFrame {

    String email, password;

    /**
     * Creates new form UserLogin
     */
    public UserLogin() {
        initComponents();
        setSize(500, 400);
        setVisible(true);
        setLocation(300, 175);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_em = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bt_log = new javax.swing.JButton();
        tf_pass = new javax.swing.JPasswordField();
        bt_for = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setFont(new java.awt.Font("Aparajita", 0, 24)); // NOI18N
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setText("Enter Email");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 14, 160, 30);
        getContentPane().add(tf_em);
        tf_em.setBounds(70, 50, 190, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setText("Enter Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 100, 140, 30);

        bt_log.setBackground(new java.awt.Color(204, 204, 255));
        bt_log.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt_log.setText("Login");
        bt_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logActionPerformed(evt);
            }
        });
        getContentPane().add(bt_log);
        bt_log.setBounds(110, 180, 130, 50);
        getContentPane().add(tf_pass);
        tf_pass.setBounds(70, 130, 220, 40);

        bt_for.setBackground(new java.awt.Color(255, 153, 153));
        bt_for.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        bt_for.setText("Forgot Password");
        bt_for.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        bt_for.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_forActionPerformed(evt);
            }
        });
        getContentPane().add(bt_for);
        bt_for.setBounds(180, 240, 190, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logActionPerformed
        if (tf_em.getText().equals("") || tf_pass.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Fill all details");

        } else {

//email= tf_em.getText();
//password= tf_pass.getText();       
            new Thread(new job()).start();        // TODO add your handling code here:
    }//GEN-LAST:event_bt_logActionPerformed
    }
    private void bt_forActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_forActionPerformed
        // TODO add your handling code here:
        ForgotPass obj = new ForgotPass();
        JOptionPane.showMessageDialog(rootPane, "you forgot your password :[ !!");
        obj.setVisible(true);
    }//GEN-LAST:event_bt_forActionPerformed

    class job implements Runnable {

        @Override
        public void run() {

            //email= tf_em.getText();
//password= tf_pass.getText();       
            try {
                // email= tf_em.getText();
//password= tf_pass.getText();       

                HttpResponse res = Unirest.get("http://"+GlobalData.host+"/UserLogin").queryString("email", tf_em.getText()).queryString("password", tf_pass.getText()).asString();
                if (res.getBody().equals("success")) {

                    JOptionPane.showMessageDialog(rootPane, "Hello user!you succesfully logged in");
                    //AdminHome obj = new AdminHome();
                    dispose();
                    WelcomeUser obj = new WelcomeUser(tf_em.getText(), tf_pass.getText());
                    obj.setVisible(true);

                } else {

                    JOptionPane.showMessageDialog(rootPane, "Sorry!You are not the user");

                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }
    }

    /**
     * @param args the command line arguments
     *
     *
     *
     *
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_for;
    private javax.swing.JButton bt_log;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tf_em;
    private javax.swing.JPasswordField tf_pass;
    // End of variables declaration//GEN-END:variables
}
